### ISSUE TITLE
How to make this language support Chinese?

### ISSUE THREAD

**Issue by JoeImJoe** [aeksco/openjscad-react#4]
![image](https://user-images.githubusercontent.com/31102806/146476759-42ea1176-2611-4aa9-956c-740a99a19f0f.png)

**Comment by aeksco** [comment]
Hi @JoeImJoe - the name plate example is just an implementation to show off the capabilities of `openjscad-react` library and isn't necessarily meant to be a functional tool by itself. Frankly I'm not sure what would need to be done to get the OpenJSCAD text-to-model function to support different character sets 🤷‍♂️  In any case I'm closing this ticket for being out-of-scope - thank you for your interest in this project!

**Comment by z3dev** [comment]
@JoeImJoe you might be interested in this small library for using TTF fonts inside a JSCAD project.

https://github.com/jscad-community/jscad-text
